#!/usr/bin/env python3
"""Generate make rules from the catalog.

The variant list lives in YAML, so the rules that build it cannot be written by
hand without duplicating that list. This emits one grouped rule per variant plus
the ARTIFACTS / THUMBNAILS variables the Makefile's targets depend on.

Writes to stdout; the Makefile redirects it to build/parts.mk and includes it.
Runs inside the pinned toolchain image -- invoke through bin/python3.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog import Part, Variant, load  # noqa: E402

HEADER = """\
# GENERATED by tools/gen_rules.py -- do not edit.
# Regenerated automatically whenever an entry.yaml changes; see the Makefile.
"""


def variant_flags(part: Part, variant: Variant) -> str:
    if variant.param_set is None:
        return ""
    return f" -p {part.params} -P {variant.param_set}"


def emit_variant(part: Part, variant: Variant, out: list[str]) -> tuple[str, str]:
    stem = part.artifact_stem(variant)
    outdir = f"$(OUT)/{part.name}"
    three_mf = f"{outdir}/{stem}.3mf"
    stl = f"{outdir}/{stem}.stl"
    metrics = f"{outdir}/{stem}.metrics.json"
    dep = f"$(BUILD)/deps/{part.name}-{variant.name}.d"
    flags = variant_flags(part, variant)

    # entry.yaml is a prerequisite because the version is baked into the output
    # filename; params.json because openscad -d does not record either.
    prereqs = [str(part.source), str(part.path / "entry.yaml")]
    if variant.param_set is not None:
        prereqs.insert(1, str(part.params))

    # Grouped target (&:, GNU make >= 4.3): one recipe, three outputs. Without
    # the grouping, deleting just the .stl would not trigger a rebuild.
    out.append(f"{three_mf} \\")
    out.append(f"{stl} \\")
    out.append(f"{metrics} &: \\")
    out.append("\t\t" + " \\\n\t\t".join(prereqs))
    out.append(f"\t@mkdir -p $(@D) $(BUILD)/deps")
    # Render to a temp path with a format-valid suffix, then rename: OpenSCAD
    # streams its output, and anything reading concurrently (the preview
    # server) must never observe a partial mesh. A '.tmp' suffix would not
    # work -- OpenSCAD infers the exporter from the extension.
    out.append(f"\t$(OPENSCAD) $(OPENSCAD_FLAGS){flags} \\")
    out.append(f"\t  -d {dep} \\")
    out.append(f"\t  -o {outdir}/.tmp-{stem}.3mf \\")
    out.append(f"\t  {part.source}")
    out.append(f"\tmv {outdir}/.tmp-{stem}.3mf {three_mf}")
    # openscad -d writes the dep file naming whatever -o was given, i.e. the
    # temp path, and records OPENSCADPATH includes as container-absolute
    # /work/... paths. Left alone, the included rule would hang dependencies
    # off a target make never builds, and name prerequisites that do not exist
    # outside the container -- so a lib/ edit would silently rebuild nothing,
    # which is precisely the fan-out case this design most needs to get right.
    out.append(f"\tsed -i -e 's|{outdir}/\\.tmp-{stem}\\.3mf|{three_mf}|' "
               f"-e 's|/work/||g' {dep}")
    out.append(f"\t$(PYTHON) tools/metrics.py {three_mf}")
    out.append("")
    out.append(f"-include {dep}")
    out.append("")
    return three_mf, metrics


def emit_thumbnail(part: Part, variant: Variant, out: list[str]) -> str:
    # Single-variant parts render to thumbnails/<part>/<part>.png, mirroring
    # how the variant suffix drops out of artifact filenames.
    png = f"$(THUMBS)/{part.name}/{variant.name}.png"
    flags = variant_flags(part, variant)
    camera = ",".join(f"{c:g}" for c in part.camera)
    prereqs = [str(part.source), str(part.path / "entry.yaml")]
    if variant.param_set is not None:
        prereqs.insert(1, str(part.params))

    out.append(f"{png}: \\")
    out.append("\t\t" + " \\\n\t\t".join(prereqs))
    out.append("\t@mkdir -p $(@D)")
    # Fixed camera, never --viewall/--autocenter: a reframe on every size change
    # would make the whole image differ and hide the actual change.
    out.append(f"\t$(OPENSCAD) --backend=manifold --render \\")
    out.append(f"\t  --imgsize=$(THUMB_SIZE) --camera={camera} \\")
    out.append(f"\t  --colorscheme=$(THUMB_COLORSCHEME){flags} \\")
    out.append(f"\t  -o $(@D)/.tmp-{variant.name}.png {part.source}")
    out.append(f"\tmv $(@D)/.tmp-{variant.name}.png $@")
    out.append("")
    return png


def main() -> int:
    parts, errors = load()
    if errors:
        for e in errors:
            print(f"gen_rules: catalog invalid: {e}", file=sys.stderr)
        return 1

    out: list[str] = [HEADER]
    artifacts: list[str] = []
    metrics: list[str] = []
    thumbs: list[str] = []

    for part in sorted(parts, key=lambda p: p.name):
        out.append(f"# ---- {part.name} (v{part.version}) "
                   f"{'-' * max(0, 50 - len(part.name) - len(part.version))}")
        out.append("")
        for variant in part.variants:
            three_mf, metrics_json = emit_variant(part, variant, out)
            artifacts += [three_mf, three_mf.replace(".3mf", ".stl"), metrics_json]
            metrics.append(metrics_json)
            thumbs.append(emit_thumbnail(part, variant, out))

    def var(name: str, values: list[str]) -> str:
        joined = " \\\n  ".join(values)
        return f"{name} := \\\n  {joined}\n" if values else f"{name} :=\n"

    out.append(var("ARTIFACTS", artifacts))
    out.append(var("METRICS", metrics))
    out.append(var("THUMBNAILS", thumbs))

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
